apiVersion: v1
kind: Service
metadata:
  name: mysql-inside
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      nodePort: 30306 # Choose a number between 30000–32767

